### ISSUE TITLE
[epic] ✅ Native Group Support

### ISSUE THREAD

**Issue by benjaminbollen** [CirclesUBI/circles-contracts-v2#10]
### Registering
- [x] a group can register in a graph, and receives a group circle node contract

### Trusting
- [x] an avatar can trust a group
  - [x] upon trusting group, its group tokens are 1-1 fungible with yours ~~`trustGroup()`~~ (simply `trust()` indiscriminately)
  - [ ] ~~#36~~
- [x] a group can trust a group
- [x] a group can trust an avatar

### Path transfers
- [x] if the group has some balances on the trust graph, they are path fungible
- [x] ~~(?) if the group has some balances (group's or avatar's), should group get called upon transfer such that it can selectively block?~~ -- already covered by trust relations?

### Wrapping / minting
- [x] mint through explicit call;
- [ ] can mint happen after path-transfer - look into pre-/post- hooks on intents
- [x] create callback to group contract to review and adjust the mint (see https://github.com/CirclesUBI/circles-contracts-v2/pull/24/commits/0cb93587513ab1ed57724fee1c0498981231b261)

### Demurrage
- [x] group tokens have the same demurrage behaviour as avatar tokens

### Unwrapping with exit fee
- [x] #34

### Burnt collateral for composing group tokens
- [x] if the exit fee was set to 100%, then collateral is burnt upon minting. No unwrapping is possible, but group tokens can be used to mint (other) group tokens
