### ISSUE TITLE
[epic] CRC re-implementation

### ISSUE THREAD

**Issue by benjaminbollen** [CirclesUBI/circles-contracts-v2#44]
- [ ] CRC implementation with inflation rather than demurrage for usage by businesses who prefer to account books in a traditional way
- [ ] two-way bridge between temporally discounted tokens and inflation-based tokens
- [ ] proposal for roadmapping: make the bridge governed so that this epic can sequenced. First the demurraged tokens can be completed with a bridge that can later be activated to the second graph of inflation-based tokens. (thoughts @shorn-gnosis)

**Comment by benjaminbollen** [comment]
this epic risks creating a big delay. Conceptually this is no longer a big item, but the math upon conversion between the two graphs needs to be dealt with carefully, and it opens a much bigger test surface that needs to be evaluated and covered. Therefore it would be prudent to consider ways in which this epic does not become a blocker for advancing on the release of temporally discounted Circles. 

note: if the conversion contract between the two graphs is permissionless then both graphs and the conversion contract need to be fully reviewed and deployed together, which creates the risk to timely releasing circles v2
