### ISSUE TITLE
[epic] ✅ Migration and Upgradability

### ISSUE THREAD

**Issue by benjaminbollen** [CirclesUBI/circles-contracts-v2#5]
**Topics under this epic**:
- [x] migration from v1 to v2 (smooth case)
- [x] edge-case for migration v1-v2 (person signs up in v1, **after** signing up in v2)
- [x] how to handle compatibility with unknown later versions, without introducing special admin keys
- [x] how to handle scalability and privacy extensions that are later on the roadmap, and also might be more vulnerable to security flaws

**key take-away**:
> we do already know that for all past and future versions, one invariant must always hold: you cannot mint more than 1 circle per hour per person.

therefore a person can register in multiple trust graphs simultaneously, we only need to ensure that the combined mint across all graphs is less or max than 1 token per hour per person.

**proposal**:
a mint splitter contract is simple and transparent to implement and can be relied upon v2+ and have knowledge about handling v1 (only 100% mint or `stopped`). It does not need upgrading because it only concerns about the one invariant rule.

**Comment by benjaminbollen** [comment]
**issues**:
- #27 
- #32
